### PR TITLE
Add workshop banner

### PR DESCRIPTION
**Pull request by Tammo-Feldmann**
## What I'm adding 
This is a quick addition of a banner to announce a workshop. 

Screenshot 2024-03-19 at 8 48 15 AM

### CODE REVIEW

**Comment by Tammo-Feldmann** [comment]
@heidimok could you please review and advise on styling? Thank you.

**Comment by heidimok** [comment]
@Tammo-Feldmann the styling is looking good with me.

Would it be possible to align the '`x`' on the right-hand side similar to this banner on the DevSeed site?
image

**Comment by Tammo-Feldmann** [comment]
Sounds great @heidimok. I made the change that you suggested and updated the screenshot above ☝️. Let me know when you're ready to merge this and we can move it to staging at any point.

**Review by heidimok — APPROVED** [review]

**Comment by heidimok** [comment]
Thank you, ready to merge

**Pull request merged**
