### PR TITLE
Add Rocket Launch Icon

### LINKED ISSUE #704: Add icon for Rocket Launch Site
In the [SOLVE campaign](http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/SOLVE/), we have `Rocket Launch Site` as one of the static platforms, so we need an icon for it.

### PR DESCRIPTION
**Pull request by LanesGood**
Closes #704

### CODE REVIEW

**Comment by willemarcel** [comment]
@LanesGood it's rendering correctly in the map legend, but not in the map. Did you add it to the Mapbox Style?

**Comment by LanesGood** [comment]
@willemarcel thanks for the reminder - `RocketIcon` is now added to the mapbox style.

**Comment by LanesGood** [comment]
Confirmed 2D map works:
image

But 3D is loading the wrong icons - will check if that is fixed in https://github.com/NASA-IMPACT/admg-casei/pull/707
image

This is the SOLVE campaign

**Comment by willemarcel** [comment]
@LanesGood I've fixed the issue with the last commit

**Review by willemarcel — APPROVED** [review]

**Pull request merged**
